version: '3.8'

services:
  mysql-backup:
    build: .
    container_name: mysql-backup
    environment:
      - MYSQL_HOST=your-mysql-server.com
      - MYSQL_PORT=3306
      - MYSQL_USER=backupuser
      - MYSQL_PASSWORD=your_secure_password
      - MYSQL_DATABASE=all  # 或指定数据库名
      - BACKUP_INTERVAL=daily  # daily, weekly, hourly, test
      - MAX_BACKUPS=7
    volumes:
      - ./backups:/backups
    restart: unless-stopped